// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgdctqmaizssrzcllwfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnZGN0cW1haXpzc3J6Y2xsd2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxOTQzODksImV4cCI6MjA1MDc3MDM4OX0.1QeR2R3R3hIJ1TubELR_F145GtXG1SSUALEDVJ-nVaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);